### ISSUE TITLE
Some IMDb titles not being detected

### ISSUE THREAD

**Issue by go2tom42** [roboticsound/Pulsarr#23]
http://www.imdb.com/title/tt6080460
http://www.imdb.com/title/tt6687948
http://www.imdb.com/title/tt1648199

**Comment by roboticsound** [comment]
This unfortunately is something that, due to way Pulsarr works, I am not able to address right now. I believe that it maybe to do with the imdb api on some lesser known titles. I may look at ways of addressing this in the future but this will require changing the way Pulsarr searches for movies and I do not want to introduce false matches.

**Comment by roboticsound** [comment]
Closing for now as there are no immediate plans to address this. If this continues to be a problem, please open another issue.
