### ISSUE TITLE
Chrome link is dead

### ISSUE THREAD

**Issue by Chiggy-Playz** [roboticsound/Pulsarr#79]
Chrome link doesnt open up the chrome store. Instead it gives 404.

**Comment by psharma04** [comment]
Hopefully a .crx upload is possible soon, so that if the Chrome Web Store does this again it won't matter as much.

**Comment by psharma04** [comment]
Until the dev uploads the .crx again, here's a link: https://share.dmca.gripe/0VufZNbmf3XHMZd8.crx

**Comment by psharma04** [comment]
You'll probably have to manually install it because Chrome doesn't allow packed extensions from outside the Web Store. To do this, clone/download this repository. Then, go to chrome://extensions and enable developer mode. Finally, click "load unpacked extension" and navigate to the cloned "Pulsarr" folder.

**Comment by Chiggy-Playz** [comment]
Yeah, I did that step a few days ago, and as expected, it works.
